apiVersion: v1
kind: Pod
metadata:
   name: multitool
   namespace: netology-net
spec:
   containers:
     - name: multitool
       image: wbitt/network-multitool
       ports:
        - containerPort: 8080