apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
  namespace: netology-net
spec:
  selector:
    app: nmt
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80    
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180